version: '3.1'

services:
  frontend:
    image: phonebook
    volumes:
      -  ./phonebook-data:/phonebook
    ports:
      - 8080:8080
      - 8088:8088
    environment:
      - JarvisConfig=/app/frontend.json
      - DYALOG_JARVIS_THREAD=DEBUG
      - RIDE_INIT=HTTP:*:8088   
  backend:
    image: phonebook
    restart: always
    volumes:
      -  ./phonebook-data:/phonebook
    ports:
      - 8089:8089
    environment:
      - JarvisConfig=/app/backend.json
      - DYALOG_JARVIS_THREAD=DEBUG
      - DYALOG_JARVIS_PORT=8081
      - RIDE_INIT=HTTP:*:8089   